### ISSUE TITLE
Run I run the test sample against cosmosdb emulator and in azure cosmosdb, I am getting an error that reference R_0["id"] cannot be located in the raw records.

### ISSUE THREAD

**Issue by mouaxiong** [ExRam/ExRam.Gremlinq#47] opened 2020-01-27 19:04 UTC
I am able to run the add methods for adding vertex records.  However, when I run the full example, the line _g.V().Drop() is throwing an exception with the following message:

ExceptionMessage :
	Gremlin Query Compilation Error: Column reference R_0["id"] cannot be located in the raw records in the current execution pipeline.
Source : Microsoft.Azure.Cosmos.Gremlin.Core

Details:
fail: test[0]
      Error executing Gremlin query V().hasLabel(_a).drop().project('id', 'label', 'type', 'properties').by(id).by(label).by(__.constant('vertex')).by(__.properties().group().by(__.label()).by(__.project('id', 'label', 'value', 'properties').by(id).by(__.label()).by(__.value()).by(__.valueMap()).fold())):
      Gremlin.Net.Driver.Exceptions.ResponseException: ScriptEvaluationError: 

Can you shed any light on this as to why I can't run this drop statement to clear the graph?  Thank you in advance.

**Comment by BenjaBobs** [comment] 2020-01-27 22:40
I believe it is the same issue as this: https://github.com/ExRam/ExRam.Gremlinq/issues/45

**Comment by danielcweber** [comment] 2020-01-28 08:28
Duplicate of #45.

**Closed by danielcweber** 2020-01-28 08:28 UTC
