### ISSUE TITLE
Unhelpful exception when doing any query to CosmosDB

### ISSUE THREAD

**Issue by Anton0123** [ExRam/ExRam.Gremlinq#86] opened 2020-06-29 19:48 UTC
Code: 
` var _g = g.UseCosmosDb("example.gremlin.cosmos.azure.com", "myDb", "myGraphName", "myPrimaryKey==");`
`var result = await _g.V().FirstAsync();`

he graph has been populated with two Vertices and one edge between them.

Expected: result equals the first vertex

Result: `await _g.V().FirstAsync()` throws an exception with message

`System.MissingMethodException: 'Method not found: 'Void Gremlin.Net.Driver.GremlinClient..ctor(Gremlin.Net.Driver.GremlinServer, Gremlin.Net.Structure.IO.GraphSON.GraphSONReader, Gremlin.Net.Structure.IO.GraphSON.GraphSONWriter, System.String, Gremlin.Net.Driver.ConnectionPoolSettings, System.Action`1<System.Net.WebSockets.ClientWebSocketOptions>)'.'`

Any ideas?

**Comment by danielcweber** [comment] 2020-06-29 20:33
Duplicate of #77 .

**Closed by danielcweber** 2020-06-29 20:33 UTC
